GMAIL_USER = "syfuddhin@gmail.com"
OPENAI_API_KEY = "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"
GMAIL_APP_PASSWORD="ohng pmze irjk byhh"